### PR TITLE
Changing to not use absolute path, plenty use absolute already

### PR DESCRIPTION
**Pull request by garyluu**
This tests if file provisioning with relative paths work.

### CODE REVIEW

**Comment by denis-yuen** [comment]
@garyluu  How long does this series of tests take to run? 
It might make sense to run both just to be sure, at last for some

**Comment by garyluu** [comment]
These 3 tests combined take less than a minute.  We have plenty of other tests that use absolute path though.

**Comment by denis-yuen** [comment]
Looks like an intemmitent network failure

**Comment by denis-yuen** [comment]
Yup, network failure. 
Essentially replicate by adding this to  /etc/hosts
```
0.0.0.0   www.dublincore.org
0.0.0.0   dublincore.org
::0       www.dublincore.org
::0       dublincore.org

```

**Comment by garyluu** [comment]
hmm...i was thinking it might've been pip requests

**Comment by denis-yuen** [comment]
Nah, I think cwltool must be reaching out to test that the metadata corresponds to valid domains or similar

**Comment by denis-yuen** [comment]
@garyluu looks like both, it looks like a Python "requests" library update broke causing similar symptoms to a host being blocked. Thanks for the heads-up

**Pull request merged**
