### PR TITLE
Workflow path backport

### PR DESCRIPTION
**Pull request by denis-yuen**
This is a backport of #865

### CODE REVIEW

**Comment by garyluu** [comment]
hmm...can't assign you as reviewer

**Comment by denis-yuen** [comment]
I'm probably too involved

**Comment by denis-yuen** [comment]
@garyluu  do you mind re-basing this, I wonder if that will let me be assigned as a reviewer and it probably should be done anyway due to the number of commits in this PR

**Comment by denis-yuen** [comment]
FYI, this seems to break bamstats using a parameter JSON like 
```
{
  "bam_input": {
        "class": "File",
        "format": "http://edamontology.org/format_2572",
        "path": "rna.SRR948778.bam"
    },
    "bamstats_report": {
        "class": "File",
        "path": "s3://oicr.temp/bamstats_report.zip"
    }
}
```

**Pull request closed without merging**
