### PR TITLE
updated logos on docs page, link to funding

### PR DESCRIPTION
**Pull request by agduncan94**
Updates the logos on the front page to match the actual Dockstore site. Also adds a link to the bottom.

Note I still have to test this on github on my own fork, but I will notify people when it is time to review.

### CODE REVIEW

**Comment by agduncan94** [comment]
Here it is running online.
https://agduncan94.github.io/

**Comment by agduncan94** [comment]
https://agduncan94.github.io/agduncan94/

**Comment by garyluu** [comment]
Steps to make it view-able on gh-pages:
- Fork repo to your own
- Rename repo to your username
- Delete master
- Copy the feature branch to master
- View it at your GitHub user page

**Comment by garyluu** [comment]
I also copied the above into the primer for future uses

**Pull request merged**
