### PR TITLE
Feature/verification expansion

### PR DESCRIPTION
**Pull request by denis-yuen**
Working on #1454

### CODE REVIEW

**Comment by denis-yuen** [comment]
Note to self: encountering rate limit for quay.io

**Comment by denis-yuen** [comment]
Not sure what's going on with coverage. 
Changed files seems to include changes from Feature/divide integration tests (#1465)  which is odd.

**Comment by garyluu** [comment]
can you mention which commits are relevant/not relevant?

**Comment by denis-yuen** [comment]
@garyluu  the cherry-picked commits are 
3402c18 and b53bd7a

**Pull request merged**
