### PR TITLE
Add FAQ about python 3

### PR DESCRIPTION
**Pull request by garyluu**
FAQ about how to run Dockstore 1.4.1 with Python 3. 

For issue #1242

### CODE REVIEW

**Comment by garyluu** [comment]
Hmm...not triggering travis.yml for some reason.

**Comment by denis-yuen** [comment]
Might be because its in your repo

**Comment by garyluu** [comment]
Hmm..Travis suddenly started again.

**Comment by garyluu** [comment]
Closing this in favor of the other PR

**Pull request closed without merging**
