### PR TITLE
Add search box

### PR DESCRIPTION
**Pull request by garyluu**
Adds a search box in the top middle area.  No index needs to be built beforehand.  All searching is done client-side.  Title is given a weight of 10.  Uses lunrjs.  Using basic bootstrap styling.

### CODE REVIEW

**Comment by agduncan94** [comment]
@garyluu @denis-yuen I'm going to do some style cleanup on this before it is merged.

**Comment by agduncan94** [comment]
@garyluu  It doesn't if the search text is set to empty

**Comment by garyluu** [comment]
FYI, search.html page that gets built by jekyll will contain the entire index in window.store in its <script></script>

**Comment by denis-yuen** [comment]
Ah, so [view-source:https://docs.dockstore.org/search.html](view-source:https://docs.dockstore.org/search.html)

**Pull request merged**
