### PR TITLE
Improve UnitOfWork annotations

### PR DESCRIPTION
**Pull request by david4096**
This PR adds `readOnly` to appropriate annotations that don't perform a write action and removes hibernate annotations from code that didn't require it.

https://www.dropwizard.io/0.6.2/maven/dropwizard-hibernate/apidocs/com/yammer/dropwizard/hibernate/UnitOfWork.html

### CODE REVIEW

**Comment by david4096** [comment]
I tried out the https://github.com/dockstore/dockstore-load-tester against this PR (`Reference` and the current state of develop (`Challenger`).

  | Reference | Challenger |  
-- | -- | -- | --
2019-04-03 15:30:40 | 2019-04-03 15:48:18 |  
io.dockstore.DockstoreWebUser | io.dockstore.DockstoreWebUser |  
322.1 | 322.2 |  
23.8 | 23.8 | +0.08 %
115.0 | 117.9 | +2.54 %
7925 | 7932 |  
250 | 250 |  
23 | 23 |

**Comment by denis-yuen** [comment]
If I'm interpreting the table correctly (matching rows with https://github.com/dockstore/dockstore-load-tester#comparing-results ) and if the results aren't flipped (is challenger the version in this branch?). 
Isn't the new version actually slower by 2.9ms rather than faster?
That's probably statistical noise though. Not sure how to explain the 7 extra requests

**Comment by denis-yuen** [comment]
Coincidentally (?) the example screenshot also has 7 more requests. 
is there a systematic off-by-seven error? 
https://raw.githubusercontent.com/dockstore/dockstore-load-tester/master/nuxeo-screenshot.png

**Comment by coverbeck** [comment]
There is some randomness to the requests which can have small implications for the number of requests.
Because the sitemap and calls to TRS v1 and v2 calls are both very expensive and unlikely to be called frequently, I only invoke them a random 5% of the time.

Also when getting a list of entries, I pick a random one to drill down into, and I think that might affect the number of calls as well.

**Comment by david4096** [comment]
| Reference | Challenger |  
-- | -- | -- | --
2019-04-04 13:54:14 | 2019-04-04 13:32:07 |  
io.dockstore.DockstoreWebUser | io.dockstore.DockstoreWebUser |  
320.2 | 318.3 |  
11.6 | 11.7 | +0.68 %
73.8 | 70.9 | -3.95 %
3813 | 3816 |  
100 | 100 |  
10 | 9 |

**Pull request merged**
